title: Julia Nguyen # your name (or website title) here
logo: "/images/linkedInPhoto.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Grad student in Master’s in Data Science at Indiana University with 5+ years experience in Legal and a passion for solving data problems.
  <br><br>
  <a href="https://www.linkedin.com/in/julia-hoa-nguyen-1260b91b4/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal 
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
