title: Julia Nguyen # your name (or website title) here
logo: "/images/profile2.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  An ex-Amazonian in Legal and currently grad student pursuing my Master’s in Data Science at Indiana University. Passionate about using making complex data accessible to drive meaningful change and create impact. Making the transition from legal to tech one algorithm at a time!
  <br><br>
  <a href="https://www.linkedin.com/in/julia-hoa-nguyen-1260b91b4/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal 
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
